[KSecretD]
Enabled=false

[Migration]
MigrateTo3rdParty=false
WalletsMigratedToSecretService=Secret Service Integration

[Wallet]
Close When Idle=false
Close on Screensaver=false
Default Wallet=Secret Service Integration
Enabled=true
First Use=false
Idle Timeout=10
Launch Manager=true
Leave Manager Open=false
Leave Open=true
Prompt on Open=true
Use One Wallet=true

[org.freedesktop.secrets]
apiEnabled=true
