[KSecretD]
Enabled=false

[Wallet]
Enabled=true
Default Wallet=Secret Service Integration

Close When Idle=false
Close on Screensaver=false
First Use=false
Launch Manager=true
Idle Timeout=10
Leave Manager Open=false
Leave Open=true
Prompt on Open=true
Use One Wallet=true

[org.freedesktop.secrets]
apiEnabled=false
