# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];



  boot = {
    # Bootloader
    loader ={
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
    };

    # Use the latest kernel packages
    kernelPackages = pkgs.linuxPackages_latest;

    # Configure initial ramdisk modules
    initrd = {
      availableKernelModules = [
        "nvme"
        "sd_mod"
        "xhci_pci"
        "usb_storage"
      ];
      kernelModules = [ ];
    };

    # Configure kernel modules
    kernelModules = [
      "amd_pstate" "kvm-amd"
      "asus-nb-wmi" "asus_wmi"
    ];

    # Blacklist specific kernel modules
    blacklistedKernelModules = [
    "uvcvideo"
    ];

    # Kernel parameters configuration
    kernelParams = [
      "acpi_backlight=native" "acpi_osi=Linux"


      # CPU optimizations
      "amd_iommu=on"
      "amd_pstate=active"  # Enable AMD P-State driver
      "processor.max_cstate=5"  # Limit C-states for better response time

      # Memory security parameters
      "page_alloc.shuffle=1"    # Helps detect memory issues earlier + Major security gain
      "init_on_free=1"          # Fill freed pages and heap objects with zeroes
      "vsyscall=none"           # Disables legacy system call interface
      "slab_nomerge"            # Disables merging of slabs of similar sizes
      "slub_debug=FZ"           # Enables sanity checks (F) and redzoning (Z)

      #"mem_sleep_default=deep" # Force deep sleep instead of s2idle
    ];

  kernel.sysctl = {
  "vm.swappiness" = 10;  # Change this value as needed (0-100) 0 makes kernel avoid swap as much as possible
  };

    # No extra module packages
    extraModulePackages = [ ];
  };

  services.fstrim = {
    enable = true;
    interval = "weekly"; # Default is weekly, which is generally sufficient
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/43aedd8b-e362-4cb3-872b-da3ea71c02c2";
      fsType = "ext4";
      options = [ "noatime" "commit=5"  ];  # Optimize for SSD
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/99F7-D86D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  services.smartd = {
    enable = true;
    devices = [
      {
        device = "/dev/nvme0n1"; # FIXME: Change this to your actual disk; use lsblk to find the appropriate value
      }
    ];
  };

  # Add zram-based swap since you have no swap configured
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 20;  # Use up to 20% of RAM for zram swap
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}